Config:
  NameNodeHost: 127.0.0.1:50070
  Port: 9001
  DataNodeId: 1
  HeartbeatInterval: 6000
  # 单位 MB
  MaxSendMsgSize: 70
  MaxRecvMsgSize: 70
  HeartBeatRetry: 3
  DataDir: /usr/golanddata/trainfs/datanode
