Config:
  Port: 50070
  NameNodeId: 1
  DataNodeHeartBeatInterval: 8000
  DataNodeHeartBeatTimeout: 20000
  # 单位 MB
  MaxSendMsgSize: 10
  MaxRecvMsgSize: 10
  DataDir: /usr/golanddata/trainfs/namenode
  # model: Single | Cluster
  Model: Single
  PeerNameNodes: [127.0.0.1:50071,127.0.0.1:50072]
